services:


    postgresql:
      image: bitnami/postgresql
      restart: always
      ports:
        - '5432:5432'
      volumes:
        - postgresql_data:/bitnami/postgresql
      environment:
        - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
        - POSTGRESQL_LOG_HOSTNAME=true
        - POSTGRESQL_REPLICATION_MODE=master
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_user
        - POSTGRESQL_USERNAME=postgres
        - POSTGRESQL_PASSWORD=postgres
        - POSTGRESQL_DATABASE=development_database
        - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_data:
    driver: local